run: build
	java -cp bin Main

build:
	javac -d bin Main.java	

# Clean para Windows
clean:
	rmdir /s /q bin 
	
git:
	git config --global user.name "NatanCancian"
	git config --global user.email "natancancian@gmail.com"